---
name: AdvancedTimerTool
description: Sistema de temporizador avançado com cache e otimização para desenvolvedores
author: Rajador, Souzaghost
discord: rajadortv
api: 2.0.0
depend: [SmartCommand]
version: 1.0.0
main: 'advancedtimertool\AdvancedTimerToolLoader'
...