#Jesus is king
---
name: AdvancedTimerTool
main: 'advancedtimertool\AdvancedTimerToolLoader'
version: 1.0.0
discord: rajadortv
author: [Rajador, Souzaghost]
description: 'Sistema de avançado de tempo'
depend: [SmartCommand]
api: 2.0.0
resources: []
...
